export const ADD_ARTICLE = "ADD_ARTICLE";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const HANDLE_HOME_VIEW_SIGNUP_CLICKED = "HANDLE_HOME_VIEW_SIGNUP_CLICKED";
export const HANDLE_HOME_VIEW_SHOW_USERS_CLICKED = "HANDLE_HOME_VIEW_SHOW_USERS_CLICKED";
export const HANDLE_HOME_VIEW_SUCCESS_USER_FETCH = "HANDLE_HOME_VIEW_SUCCESS_USER_FETCH";
export const HANDLE_HOME_VIEW_FAILURE_USER_FETCH = "HANDLE_HOME_VIEW_FAILURE_USER_FETCH";
export const HANDLE_HOME_VIEW_LOADING = "HANDLE_HOME_VIEW_LOADING";
